/* Les recettes.

   Simples, faisables un soir de semaine, avec ce qu'on trouve ici. Les
   valeurs sont données par portion et restent des ordres de grandeur — une
   cuillère d'huile de plus change tout.

   Pas de photos : les images pèsent lourd et il faudrait les héberger. Une
   couleur et un emoji par recette suffisent à s'y retrouver. */

export type CategorieRecette = 'petit-dejeuner' | 'dejeuner' | 'diner' | 'encas' | 'rompre'

export type Recette = {
  id: string
  nom: string
  categorie: CategorieRecette
  emoji: string
  couleur: string
  minutes: number
  portions: number
  kcal: number
  proteines: number
  glucides: number
  lipides: number
  etiquettes: string[]
  ingredients: string[]
  etapes: string[]
}

export const ETIQUETTES = [
  'Rapide',
  'Riche en protéines',
  'Peu de glucides',
  'Léger',
  'Végétarien',
]

export const CATEGORIES_RECETTES: Array<{ id: CategorieRecette; nom: string }> = [
  { id: 'petit-dejeuner', nom: 'Petit-déjeuner' },
  { id: 'dejeuner', nom: 'Déjeuner' },
  { id: 'diner', nom: 'Dîner' },
  { id: 'encas', nom: 'En-cas' },
  { id: 'rompre', nom: 'Pour rompre le jeûne' },
]

export const RECETTES: Recette[] = [
  /* ---------- petit-déjeuner ---------- */
  {
    id: 'oeufs-herbes',
    nom: 'Œufs brouillés aux herbes',
    categorie: 'petit-dejeuner',
    emoji: '🍳',
    couleur: 'var(--miel-pale)',
    minutes: 10,
    portions: 1,
    kcal: 290,
    proteines: 20,
    glucides: 2,
    lipides: 22,
    etiquettes: ['Rapide', 'Riche en protéines', 'Peu de glucides'],
    ingredients: ['3 œufs', '1 cuillère à café d’huile', 'Ciboulette ou persil', 'Sel, poivre'],
    etapes: [
      'Battre les œufs à la fourchette avec le sel et le poivre.',
      'Chauffer l’huile à feu doux — c’est le feu doux qui rend les œufs crémeux.',
      'Verser et remuer sans arrêt jusqu’à ce que ça prenne, puis retirer du feu.',
      'Ajouter les herbes hors du feu.',
    ],
  },
  {
    id: 'bol-fromage-blanc',
    nom: 'Bol de fromage blanc et fruits',
    categorie: 'petit-dejeuner',
    emoji: '🍓',
    couleur: 'var(--argile-pale)',
    minutes: 5,
    portions: 1,
    kcal: 240,
    proteines: 18,
    glucides: 26,
    lipides: 6,
    etiquettes: ['Rapide', 'Riche en protéines', 'Végétarien'],
    ingredients: ['200 g de fromage blanc', '1 fruit de saison', '1 cuillère à soupe de flocons d’avoine', 'Cannelle'],
    etapes: [
      'Verser le fromage blanc dans un bol.',
      'Couper le fruit par-dessus.',
      'Parsemer les flocons d’avoine et la cannelle.',
    ],
  },
  {
    id: 'omelette-thon',
    nom: 'Omelette au thon',
    categorie: 'petit-dejeuner',
    emoji: '🐟',
    couleur: 'var(--olive-pale)',
    minutes: 12,
    portions: 1,
    kcal: 330,
    proteines: 34,
    glucides: 3,
    lipides: 19,
    etiquettes: ['Riche en protéines', 'Peu de glucides'],
    ingredients: ['2 œufs', '80 g de thon au naturel égoutté', '1/2 oignon', 'Sel, poivre'],
    etapes: [
      'Faire revenir l’oignon émincé deux minutes.',
      'Ajouter le thon émietté, mélanger.',
      'Verser les œufs battus, couvrir et laisser prendre à feu doux.',
    ],
  },
  {
    id: 'porridge-banane',
    nom: 'Porridge d’avoine à la banane',
    categorie: 'petit-dejeuner',
    emoji: '🥣',
    couleur: 'var(--miel-pale)',
    minutes: 8,
    portions: 1,
    kcal: 310,
    proteines: 11,
    glucides: 52,
    lipides: 6,
    etiquettes: ['Végétarien'],
    ingredients: ['40 g de flocons d’avoine', '200 ml de lait', '1 banane', 'Cannelle'],
    etapes: [
      'Chauffer le lait avec les flocons, cinq minutes à feu doux en remuant.',
      'Écraser la moitié de la banane dedans, garder le reste en rondelles.',
      'Servir avec la cannelle.',
    ],
  },
  {
    id: 'smoothie-papaye',
    nom: 'Smoothie papaye-coco',
    categorie: 'petit-dejeuner',
    emoji: '🥤',
    couleur: 'var(--argile-pale)',
    minutes: 5,
    portions: 1,
    kcal: 220,
    proteines: 5,
    glucides: 34,
    lipides: 8,
    etiquettes: ['Rapide', 'Végétarien'],
    ingredients: ['1/2 papaye', '100 ml de lait de coco léger', '1 citron vert', 'Glaçons'],
    etapes: [
      'Mettre la papaye, le lait de coco et le jus du citron dans le mixeur.',
      'Mixer avec les glaçons jusqu’à ce que ce soit lisse.',
    ],
  },

  /* ---------- déjeuner ---------- */
  {
    id: 'poisson-cru-leger',
    nom: 'Poisson cru allégé',
    categorie: 'dejeuner',
    emoji: '🐠',
    couleur: 'var(--olive-pale)',
    minutes: 20,
    portions: 2,
    kcal: 340,
    proteines: 30,
    glucides: 9,
    lipides: 20,
    etiquettes: ['Riche en protéines', 'Peu de glucides'],
    ingredients: [
      '400 g de thon frais',
      '4 citrons verts',
      '150 ml de lait de coco léger',
      'Concombre, tomate, oignon vert',
      'Sel',
    ],
    etapes: [
      'Couper le thon en cubes et le faire mariner dix minutes dans le jus de citron.',
      'Égoutter le jus en trop — c’est lui qui « cuit » le poisson.',
      'Ajouter les légumes coupés fin, puis le lait de coco.',
      'Servir tout de suite, bien frais.',
    ],
  },
  {
    id: 'salade-thon-haricots',
    nom: 'Salade de thon et haricots',
    categorie: 'dejeuner',
    emoji: '🥗',
    couleur: 'var(--olive-pale)',
    minutes: 15,
    portions: 1,
    kcal: 380,
    proteines: 32,
    glucides: 28,
    lipides: 14,
    etiquettes: ['Riche en protéines', 'Rapide'],
    ingredients: [
      '100 g de thon au naturel',
      '150 g de haricots blancs cuits',
      'Tomates, oignon rouge',
      '1 cuillère à soupe d’huile d’olive, vinaigre',
    ],
    etapes: [
      'Rincer les haricots, les mettre dans un saladier.',
      'Ajouter le thon égoutté, les tomates et l’oignon coupés.',
      'Assaisonner et laisser reposer dix minutes avant de manger.',
    ],
  },
  {
    id: 'poulet-riz-complet',
    nom: 'Poulet grillé, riz complet',
    categorie: 'dejeuner',
    emoji: '🍗',
    couleur: 'var(--miel-pale)',
    minutes: 30,
    portions: 2,
    kcal: 470,
    proteines: 40,
    glucides: 45,
    lipides: 12,
    etiquettes: ['Riche en protéines'],
    ingredients: [
      '300 g de blanc de poulet',
      '150 g de riz complet (cru)',
      'Citron, ail, paprika',
      '1 cuillère à soupe d’huile',
    ],
    etapes: [
      'Faire mariner le poulet avec l’ail, le paprika et le jus de citron, quinze minutes.',
      'Cuire le riz pendant ce temps.',
      'Griller le poulet cinq à six minutes de chaque côté.',
      'Laisser reposer deux minutes avant de trancher : la viande reste tendre.',
    ],
  },
  {
    id: 'wok-legumes-poulet',
    nom: 'Wok de légumes au poulet',
    categorie: 'dejeuner',
    emoji: '🥢',
    couleur: 'var(--olive-pale)',
    minutes: 20,
    portions: 2,
    kcal: 350,
    proteines: 33,
    glucides: 22,
    lipides: 13,
    etiquettes: ['Rapide', 'Riche en protéines'],
    ingredients: [
      '300 g de poulet en lanières',
      'Chou, carotte, poivron, oignon vert',
      '2 cuillères à soupe de sauce soja',
      'Gingembre, ail',
    ],
    etapes: [
      'Faire saisir le poulet à feu vif deux minutes, réserver.',
      'Jeter les légumes dans le wok très chaud, remuer sans arrêt trois minutes.',
      'Remettre le poulet, ajouter la sauce soja, l’ail et le gingembre.',
      'Servir aussitôt, les légumes doivent rester croquants.',
    ],
  },
  {
    id: 'salade-poulpe',
    nom: 'Salade de poulpe au citron',
    categorie: 'dejeuner',
    emoji: '🐙',
    couleur: 'var(--canard-pale)',
    minutes: 25,
    portions: 2,
    kcal: 260,
    proteines: 26,
    glucides: 12,
    lipides: 11,
    etiquettes: ['Léger', 'Riche en protéines'],
    ingredients: ['400 g de poulpe cuit', 'Concombre, tomate, oignon', 'Citron vert', 'Huile d’olive, persil'],
    etapes: [
      'Couper le poulpe en morceaux.',
      'Ajouter les légumes en dés.',
      'Arroser de citron et d’un filet d’huile, laisser une heure au frais.',
    ],
  },
  {
    id: 'bol-quinoa-crevettes',
    nom: 'Bol de quinoa aux crevettes',
    categorie: 'dejeuner',
    emoji: '🍤',
    couleur: 'var(--argile-pale)',
    minutes: 25,
    portions: 2,
    kcal: 400,
    proteines: 30,
    glucides: 40,
    lipides: 12,
    etiquettes: ['Riche en protéines'],
    ingredients: ['150 g de quinoa (cru)', '250 g de crevettes', 'Avocat', 'Citron, coriandre'],
    etapes: [
      'Cuire le quinoa quinze minutes, égoutter.',
      'Poêler les crevettes deux minutes de chaque côté.',
      'Monter le bol : quinoa, crevettes, avocat en lamelles, citron et coriandre.',
    ],
  },

  /* ---------- dîner ---------- */
  {
    id: 'poisson-vapeur',
    nom: 'Poisson vapeur au gingembre',
    categorie: 'diner',
    emoji: '🍲',
    couleur: 'var(--olive-pale)',
    minutes: 20,
    portions: 2,
    kcal: 240,
    proteines: 34,
    glucides: 6,
    lipides: 8,
    etiquettes: ['Léger', 'Peu de glucides', 'Riche en protéines'],
    ingredients: ['2 filets de mahi mahi', 'Gingembre frais', 'Oignon vert', 'Sauce soja', 'Citron vert'],
    etapes: [
      'Poser les filets dans le panier vapeur avec le gingembre en fines lamelles.',
      'Cuire huit à dix minutes selon l’épaisseur.',
      'Arroser de sauce soja et de citron, parsemer d’oignon vert.',
    ],
  },
  {
    id: 'omelette-legumes',
    nom: 'Omelette aux légumes',
    categorie: 'diner',
    emoji: '🍳',
    couleur: 'var(--miel-pale)',
    minutes: 15,
    portions: 2,
    kcal: 280,
    proteines: 20,
    glucides: 10,
    lipides: 18,
    etiquettes: ['Végétarien', 'Peu de glucides', 'Rapide'],
    ingredients: ['4 œufs', 'Courgette, poivron, oignon', '1 cuillère à soupe d’huile', 'Herbes'],
    etapes: [
      'Faire revenir les légumes coupés en dés jusqu’à ce qu’ils soient tendres.',
      'Verser les œufs battus, baisser le feu et couvrir.',
      'Retirer quand le dessus est juste pris.',
    ],
  },
  {
    id: 'soupe-legumes',
    nom: 'Soupe de légumes maison',
    categorie: 'diner',
    emoji: '🥕',
    couleur: 'var(--miel-pale)',
    minutes: 35,
    portions: 4,
    kcal: 130,
    proteines: 4,
    glucides: 22,
    lipides: 3,
    etiquettes: ['Léger', 'Végétarien'],
    ingredients: ['Carottes, courgettes, potiron, poireau', '1 oignon', '1 litre d’eau', 'Sel, poivre, laurier'],
    etapes: [
      'Couper tous les légumes en morceaux réguliers.',
      'Couvrir d’eau, saler, ajouter le laurier.',
      'Cuire trente minutes, puis mixer.',
      'Le soir, une grande assiette de soupe cale sans peser.',
    ],
  },
  {
    id: 'curry-poulet-leger',
    nom: 'Curry de poulet léger',
    categorie: 'diner',
    emoji: '🍛',
    couleur: 'var(--argile-pale)',
    minutes: 30,
    portions: 3,
    kcal: 330,
    proteines: 32,
    glucides: 14,
    lipides: 16,
    etiquettes: ['Riche en protéines'],
    ingredients: [
      '450 g de poulet',
      '150 ml de lait de coco léger',
      'Curry, ail, gingembre',
      'Courgette, poivron',
    ],
    etapes: [
      'Saisir le poulet, réserver.',
      'Faire revenir les épices avec l’ail et le gingembre trente secondes.',
      'Ajouter les légumes, le lait de coco, puis le poulet.',
      'Laisser mijoter quinze minutes à couvert.',
    ],
  },
  {
    id: 'papillote-mahi',
    nom: 'Papillote de mahi mahi',
    categorie: 'diner',
    emoji: '🐟',
    couleur: 'var(--olive-pale)',
    minutes: 25,
    portions: 2,
    kcal: 250,
    proteines: 33,
    glucides: 8,
    lipides: 9,
    etiquettes: ['Léger', 'Riche en protéines'],
    ingredients: ['2 filets de mahi mahi', 'Tomates cerises, courgette', 'Citron, thym', 'Filet d’huile d’olive'],
    etapes: [
      'Poser chaque filet sur une feuille de papier cuisson.',
      'Ajouter les légumes en rondelles, le citron, le thym et un filet d’huile.',
      'Fermer hermétiquement et cuire vingt minutes au four à 200 °C.',
    ],
  },
  {
    id: 'boeuf-haricots',
    nom: 'Sauté de bœuf aux haricots verts',
    categorie: 'diner',
    emoji: '🥩',
    couleur: 'var(--argile-pale)',
    minutes: 20,
    portions: 2,
    kcal: 360,
    proteines: 35,
    glucides: 12,
    lipides: 18,
    etiquettes: ['Riche en protéines', 'Peu de glucides'],
    ingredients: ['300 g de bœuf en lanières', '400 g de haricots verts', 'Ail', 'Sauce soja'],
    etapes: [
      'Cuire les haricots huit minutes à l’eau bouillante salée, égoutter.',
      'Saisir le bœuf à feu très vif deux minutes.',
      'Ajouter les haricots, l’ail et la sauce soja, remuer une minute.',
    ],
  },

  /* ---------- en-cas ---------- */
  {
    id: 'yaourt-amandes',
    nom: 'Yaourt et amandes',
    categorie: 'encas',
    emoji: '🥜',
    couleur: 'var(--miel-pale)',
    minutes: 2,
    portions: 1,
    kcal: 180,
    proteines: 9,
    glucides: 9,
    lipides: 12,
    etiquettes: ['Rapide', 'Végétarien'],
    ingredients: ['1 yaourt nature', '15 g d’amandes'],
    etapes: ['Mélanger. C’est tout.'],
  },
  {
    id: 'oeufs-durs',
    nom: 'Œufs durs',
    categorie: 'encas',
    emoji: '🥚',
    couleur: 'var(--olive-pale)',
    minutes: 10,
    portions: 1,
    kcal: 155,
    proteines: 13,
    glucides: 1,
    lipides: 11,
    etiquettes: ['Riche en protéines', 'Peu de glucides'],
    ingredients: ['2 œufs', 'Sel, poivre'],
    etapes: [
      'Plonger les œufs dans l’eau bouillante neuf minutes.',
      'Passer sous l’eau froide : ils s’écalent tout seuls.',
      'À garder au frigo pour les fringales.',
    ],
  },
  {
    id: 'batonnets-legumes',
    nom: 'Bâtonnets de légumes',
    categorie: 'encas',
    emoji: '🥕',
    couleur: 'var(--miel-pale)',
    minutes: 5,
    portions: 1,
    kcal: 90,
    proteines: 5,
    glucides: 10,
    lipides: 3,
    etiquettes: ['Léger', 'Végétarien', 'Rapide'],
    ingredients: ['Carotte, concombre, poivron', '2 cuillères à soupe de fromage blanc', 'Citron, herbes'],
    etapes: [
      'Couper les légumes en bâtonnets.',
      'Mélanger le fromage blanc avec le citron et les herbes pour tremper.',
    ],
  },
  {
    id: 'fruit-noix',
    nom: 'Un fruit et une poignée de noix',
    categorie: 'encas',
    emoji: '🍎',
    couleur: 'var(--argile-pale)',
    minutes: 1,
    portions: 1,
    kcal: 210,
    proteines: 5,
    glucides: 22,
    lipides: 12,
    etiquettes: ['Rapide', 'Végétarien'],
    ingredients: ['1 fruit', '20 g de noix ou d’amandes'],
    etapes: [
      'Le sucre du fruit passe moins vite dans le sang quand il est accompagné de gras.',
      'La poignée, c’est la vôtre — pas le sachet entier.',
    ],
  },

  /* ---------- pour rompre le jeûne ---------- */
  {
    id: 'bouillon-legumes',
    nom: 'Bouillon de légumes',
    categorie: 'rompre',
    emoji: '🍵',
    couleur: 'var(--olive-pale)',
    minutes: 10,
    portions: 1,
    kcal: 60,
    proteines: 2,
    glucides: 8,
    lipides: 2,
    etiquettes: ['Léger', 'Végétarien'],
    ingredients: ['Bouillon de légumes maison', 'Gingembre', 'Oignon vert'],
    etapes: [
      'Chauffer le bouillon avec le gingembre.',
      'Le boire lentement : c’est ce qui réveille la digestion en douceur.',
      'Le vrai repas vient vingt minutes après.',
    ],
  },
  {
    id: 'yaourt-fruits-rompre',
    nom: 'Yaourt et fruits frais',
    categorie: 'rompre',
    emoji: '🥣',
    couleur: 'var(--argile-pale)',
    minutes: 5,
    portions: 1,
    kcal: 190,
    proteines: 10,
    glucides: 26,
    lipides: 5,
    etiquettes: ['Rapide', 'Végétarien'],
    ingredients: ['1 yaourt nature', 'Fruits frais coupés'],
    etapes: [
      'Un premier repas léger évite le coup de barre qui suit un gros repas de rupture.',
      'Mélanger et manger doucement.',
    ],
  },
  {
    id: 'oeuf-poche-avocat',
    nom: 'Œuf poché et avocat',
    categorie: 'rompre',
    emoji: '🥑',
    couleur: 'var(--olive-pale)',
    minutes: 10,
    portions: 1,
    kcal: 280,
    proteines: 12,
    glucides: 8,
    lipides: 22,
    etiquettes: ['Riche en protéines', 'Peu de glucides'],
    ingredients: ['1 œuf', '1/2 avocat', 'Citron, sel, poivre'],
    etapes: [
      'Pocher l’œuf trois minutes dans l’eau frémissante vinaigrée.',
      'Écraser l’avocat avec le citron.',
      'Poser l’œuf dessus. Des protéines et du gras : la faim ne revient pas dans l’heure.',
    ],
  },
]

export const recetteParId = (id: string) => RECETTES.find((r) => r.id === id) ?? null

/** La recette du jour : la même toute la journée, différente demain. */
export function recetteDuJour(clef: string): Recette {
  const somme = [...clef].reduce((total, lettre) => total + lettre.charCodeAt(0), 0)
  return RECETTES[somme % RECETTES.length]
}
